from type_content.type_class import *

normal_type = NormalType()
fire_type = FireType()
water_type = WaterType()
grass_type = GrassType()
electric_type = ElectricType()
fighting_type = FightingType()
ice_type = IceType()
poison_type = PoisonType()
ground_type = GroundType()
flying_type = FlyingType()
psychic_type = PsychicType()
bug_type = BugType()
rock_type = RockType()
ghost_type = GhostType()
dragon_type = DragonType()
dark_type = DarkType()
steel_type = SteelType()
fairy_type = FairyType()